feat: add tenantId to both create process and publish message commands
camunda-community-hub/zeebe-client-csharp pull request #652
Opened 2024-02-14 09:27 UTC by SevereCalamari

Allows for the passing of tenantId in the request for creating a new process and publishing a message. Useful in a multitenancy environment

closes #

2024-02-14 09:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/camunda-community-hub/zeebe-client-csharp?pullRequest=652) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/camunda-community-hub/zeebe-client-csharp?pullRequest=652) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/camunda-community-hub/zeebe-client-csharp?pullRequest=652) it.</sub>

2024-02-16 14:44 UTC, Zelldon requested changes
Thanks for your contribution please add some tests or extend existing you can take a look at [Client.UnitTest ](https://github.com/camunda-community-hub/zeebe-client-csharp/tree/main/Client.UnitTests)

2024-05-17 06:56 UTC, Thilo1 commented
Hello, whats the status here ? Can it be merged?

2024-05-23 08:52 UTC, Zelldon commented
Hey @Thilo1 as long as we have no tests for it I will not merge this PR. Feel free to take this over and contribute a new PR :)

2025-02-07 22:35 UTC, closed without merging